version: '2.1'

networks:
  shared-network:
    driver: bridge

services:
  roach:
    container_name: roach
    networks:
      - shared-network
    image: cockroachdb/cockroach:v1.1.3
    command: start --insecure
    ports:
      - "26257:26257"
      - "8080:8080"
    volumes:
      - ./cockroach-data/roach1:/cockroach/cockroach-data
  api:
    container_name: api
    networks:
      - shared-network
    image: ecom/api-amd64:1.0
    ports:
      - 1323:1323
    environment:
      - HOST_ADDR=:80