version: '2.1'

networks:
  shared-network:
    driver: bridge

services:
  roach:
    container_name: roach
    networks:
      - shared-network
    image: cockroachdb/cockroach:v1.1.3
    command: start --insecure
    ports:
      - "26257:26257"
      - "8080:8080"
    volumes:
      - ./cockroach-data/roach1:/cockroach/cockroach-data
  api:
    container_name: api
    networks:
      - shared-network
    image: ecom/api-amd64:1.0
    ports:
      - 1323:1323
    environment:
      - HOST_ADDR=:80
      - DB_ADDR=mongodb://sourav212:Mft678sSQSbxp9qI@allabouttaxes-shard-00-00-xcig1.mongodb.net:27017,allabouttaxes-shard-00-01-xcig1.mongodb.net:27017,allabouttaxes-shard-00-02-xcig1.mongodb.net:27017/admin
      - DB_REPLICA_1=allabouttaxes-shard-00-00-xcig1.mongodb.net:27017
      - DB_REPLICA_2=allabouttaxes-shard-00-01-xcig1.mongodb.net:27017
      - DB_REPLICA_3=allabouttaxes-shard-00-02-xcig1.mongodb.net:27017
      - DB_ADMIN=admin
      - DB_USERNAME=sourav212
      - DB_PASSWORD=Mft678sSQSbxp9qI
      - FACEBOOK_CLIENT_ID=356500761925864
      - FACEBOOK_CLIENT_SECRET=3f90e662f0a9b3f2b400a2493d041dde
      - GOOGLE_CLIENT_ID=1009406741570-ueinnk3jgko4tuq3bv5oohna447dp8ra.apps.googleusercontent.com
      - GOOGLE_CLIENT_SECRET=pfFEjM-sciNEGCzJTmKk8t-4
      - AWS_ACCESS_KEY_ID=AKIA5F2GIWKKBRLCGN2F
      - AWS_SECRET_ACCESS_KEY=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
      - AWS_REGION=us-east-1
      - AWS_S3_BUCKET_NAME=aat-post-images
      - AWS_S3_BUCKET_URL=https://aat-post-images.s3.us-east-1.amazonaws.com/
      - ELASTIC_SEARCH_URL=https://search-aat-es-uweywnkci5hwr2ujjjfxrdersy.us-east-1.es.amazonaws.com
  
  